[lib]
proc-macro = true
[package]
name = "hellow-macro-derive"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sync = "1.0"
quote = "1.0"
